### ISSUE TITLE
compress_raster not working in v2.0.0

### ISSUE THREAD

**Issue by cefect** [jblindsay/whitebox-tools#220]
Firstly, thank you for the excellent toolbox.

 I just migrated from v1.4.0 to v2.0.0 and am now unable to generate uncompressed rasters using the BreachDepressionsLeastCost tool (I did not test other tools). I tried using  the --compress_raster='False' flag and modifying the settings.json to "compress_rasters": false. Both still produce a raster with 'DEFLATE' compression. 

Using whitebox_tools.exe from command line on Windows 10.

**Comment by brownag** [comment]
I believe `--compress_rasters` is just a flag, no = or value needed. If you don't want the result compressed, then you don't add the flag.

**Comment by Afrancioni** [comment]
Hi @cefect, Thank you for raising this issue. We have addressed this issue and a fix has been implemented. It will be available in next open core release of WhiteboxTools. We are aiming for the end of April or early May. I will keep the issue open until it is fixed. See issue #233. If you require the fixed functionality, you can download and compile the source code.

**Comment by cefect** [comment]
Just installed v2.1.0 and this still isn't fixed. 

@brownag, omitting the flag still returns a result with DEFLATE compression

**Comment by brownag** [comment]
@cefect `--compress_rasters=FALSE` seems to work for me on 2.1.0. I think I was mistaken that this can be used as a flag on more recent versions of WBT. The = and value are necessary, and in some cases the default may be TRUE?

If you are using the --compress_rasters=FALSE, perhaps you have a settings.json file with it still set to TRUE in your working directory?
