### ISSUE TITLE
Question about HorizonAngle

### ISSUE THREAD

**Issue by jepaki** [jblindsay/whitebox-tools#321]
Hello! I am using Whitebox Tools on Ubuntu 20 in Python via the PIP package mentioned on this page: https://www.whiteboxgeo.com/manual/wbt_book/python_scripting/scripting.html 

I have a question about how the HorizonAngle function works.  I have been working with some lunar DEM data and I'd like to compute some shadows with the information produced by HorizonAngle, but the outputs I'm getting are leading me to believe that I don't understand something.  Below is an image of the results of running HorizonAngle on the same DEM with two azimuth values, 0 and 360.  Since 0 and 360 are the same locations, I would expect the returned horizon angle raster to be identical, but they are more like the inverse of each other.  

![Site06_final_adj_5mpp_surf_clip_new_horizon_compare](https://user-images.githubusercontent.com/102386809/215581355-77629c04-322c-4240-ba09-c4c22e0efe9b.png)

Could you help me understand why these outputs are not identical?  This is the [DEM I'm using](https://drive.google.com/file/d/1Zo2XtoTplVtOIAXi3IBbmJvkcHf2sK4i/view?usp=sharing), and here's the code I used to generate this plot:

```
from pathlib import Path
import rasterio as rio
from rasterio.plot import show
import matplotlib.pyplot as plt
from whitebox import WhiteboxTools

data_dir = Path.cwd().joinpath("output")
dem_file = data_dir.joinpath("Site06_final_adj_5mpp_surf_clip_new.tif")
hs_file = data_dir.joinpath(dem_file.stem+"_hillshade.tif")
az0_file = data_dir.joinpath(dem_file.stem+"_az0.tif")
az360_file = data_dir.joinpath(dem_file.stem+"_az360.tif")

wbt = WhiteboxTools()
wbt.hillshade(dem_file, hs_file, azimuth=0, altitude=20)
wbt.horizon_angle(dem_file, az0_file, azimuth=0)
wbt.horizon_angle(dem_file, az360_file, azimuth=360)

dem_ds = rio.open(dem_file)
hs_ds = rio.open(hs_file)
az0_ds = rio.open(az0_file)
az360_ds = rio.open(az360_file)

fig, axs = plt.subplots(2, 2, figsize=(8, 8))
show(dem_ds, ax=axs[0, 0])
axs[0, 0].set_title("DEM")
show(hs_ds, ax=axs[0, 1])
axs[0, 1].set_title("Hillshade")

bounds = az0_ds.bounds
im = axs[1, 0].imshow(az0_ds.read(1), extent=(bounds.left, bounds.right, bounds.bottom, bounds.top), cmap="Greys")
axs[1, 0].set_title("Az=0")
plt.colorbar(im, ax=axs[1, 0])

im = axs[1, 1].imshow(az360_ds.read(1), extent=(bounds.left, bounds.right, bounds.bottom, bounds.top), cmap="Greys")
axs[1, 1].set_title("Az=360")
plt.colorbar(im, ax=axs[1, 1])

plt.tight_layout()
plot_file = data_dir.joinpath(dem_file.stem+"_horizon_compare.png")
plt.savefig(plot_file)
plt.show()


```

Thank you!

**Comment by jblindsay** [comment]
I think you're experiencing the [pseudoscopic illusion](https://www.science.org/doi/10.1126/science.194.4263.374.a).

**Comment by jblindsay** [comment]
Actually, you're right that 0 and 360 should produce the same results. Let me look into this more...

**Comment by jblindsay** [comment]
I just submitted a pull request that fixes this issue. When the azimuth was being converted to a line slope, 360 and 0 were treated as having the same slope but opposite directions. It's been resolved now and will be available in the next public release. Thanks for reporting the issue.

**Comment by jepaki** [comment]
No problem, thanks for the fix!

**Comment by jepaki** [comment]
Hello again!  Just today I cloned the whitebox-tools repo and built it with cargo, and I wanted to let you know that I'm still seeing odd behavior with the HorizonAngle function around an azimuth of 0.  I now see that azimuths of 0 and 360 yield the same results, but both 0 and 360 seem to give very different results from nearby angles, like 1 or 359.  Here's an image for reference:

![Site06_final_adj_5mpp_surf_clip_new_horizon_compare](https://user-images.githubusercontent.com/102386809/220456144-8c7bdbbf-6c6c-4e8d-9fca-7a715bc0d0f0.png)

The code that generated this image is the same as above, just with the two azimuth angles in the wbt.horizon_angle call set to 0 and 1.

**Comment by NicolaiMogensen** [comment]
I'm experiencing the same result. It seems that Azimuth(0) and Azimuth(180) are identical. So the Azimuth(0) and Azimuth(360) for some reason "starts/ends" at Azimuth(180). But if you go one degree further, its correct again.

**Comment by mmiler** [comment]
I am experiencing the same problem. Look at the image, 0 degress is totally different than others and it shouldn't be.
![ezgif-3-60279ed235](https://github.com/jblindsay/whitebox-tools/assets/1788784/62adf11b-0663-4293-8153-18016e9e1f39)
